services:
  postgres:
    image: 'postgres'
    env_file:
      - ./backend/docker.env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DOCKER_ENV: true
    ports:
      - '80:80'
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  db_data: