services:
  redis:
    image: 'redis:8'
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  postgres:
    image: 'postgres:17'
    env_file:
      - ./backend/docker.env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  backend:
    build: ./backend
    environment:
      DOCKER_ENV: true
    env_file:
      - ./backend/docker.env
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on:
      - backend

  centrifugo:
    image: centrifugo/centrifugo:v6
    environment:
      DOCKER_ENV: true
    env_file:
      - ./backend/docker.env
    volumes:
      - ./centrifugo-config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - '8081:8081'
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - backend

volumes:
  db_data:
  redis_data:
  centrifugo-config.json:
